
lirlo:
  security:
    jwt:
      signingKey: lirlo
      header: Authorization
  swagger-config:
    enable-swagger: true
    dockets:
      - group-name: 基础
        bean-name: docket1
        api-base-package: com.lirlo.baseplat.core.base
        version: v1
      - group-name: 系统
        bean-name: docket2
        api-base-package: com.lirlo.baseplat.core.system
        version: v1
      - group-name: 权限管理
        bean-name: docket3
        api-base-package: com.lirlo.baseplat.auth.security
        version: v1
    title: basePlat
    version: 1.0.0
    description: baseplat-auth
mybatis-plus:
  type-aliases-package: com.lirlo.baseplat
  mapper-locations:
    - classpath*:com/lirlo/baseplat/**/mapper/**/xml/*Mapper.xml
    - classpath:/META-INF/admin-mybatis-mappings/*.xml
    - classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration-properties:
    prefix:
    boolValue: TRUE
    blobType: BLOB
spring:
  datasource:
    #   数据源基本配置
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lwf?serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   Druid数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    database: 0
    password:
    cluster:
      nodes: 127.0.0.1:6379
server:
  port: 9091
  servlet:
    context-path: /auth



